### PR TITLE
Point to Wazimap package

### LINKED ISSUE #19: Point to Wazimap package
**Describe the bug**
Currently we're pointing to our own forked version of Wazimap.

**Expected behavior**
It would be better to point to the one OpenUpSA has i.e `wazimap` on pip.

If there is an issue we can send OpenUpSA a PR for, we should do that.

**Additional context**
Comparison: https://github.com/OpenUpSA/wazimap/compare/master...CodeForAfricaLabs:master

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Currently we're pointing to our own forked version of Wazimap. It
would be better to point to the one OpenUpSA has i.e wazimap on pip.

Fixes #19 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Looking at the [Diff](https://github.com/OpenUpSA/wazimap/compare/master...CodeForAfricaLabs:master) between our fork and OpenUpSA's @phillipahereza, I don't think we're losing anything with this switch.

**Comment by phillipahereza** [comment]
@kilemensi there was an issue with the migrations where wazimap tried to create a geo column in the DB yet it already exists, that's what I had removed https://github.com/CodeForAfricaLabs/wazimap/commit/279512cf682b6bc5e95ffb02e4e40f7f2392dbea

**Comment by kilemensi** [comment]
Thanks @phillipahereza , let me invest it further to see if it's PR we need to send to OpenUpSA or it's something we can fix on HURUmap.

**Comment by kilemensi** [comment]
OpenUpSA/wazimap#132 fixed the migration issue @phillipahereza.

**Comment by kilemensi** [comment]
Yeah @DavidLemayian, that would avoid any unforeseen issues. I've pinned the dependency to https://github.com/OpenUpSA/wazimap/commit/2cdc95447c95f20d1ba9bb2e272eef25075e14ff.

**Pull request merged**
